name: Build

on:
  schedule:
    - cron: '0 0 * * SUN' # Runs every Sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v1

      - shell: bash
        run: sudo apt-get update

      - name: QEMU
        run: sudo apt-get install -y qemu-user-static binfmt-support

      - run: docker buildx create --use

      - name: Icinga Web 2
        run: git clone https://github.com/Icinga/icingaweb2.git

      - name: Build
        run: ./build.bash ./icingaweb2 release all
