name: Build

on:
  schedule:
    - cron: '0 0 * * SUN' # Runs every Sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v1

      - shell: bash
        run: sudo apt-get update

      - name: QEMU
        run: sudo apt-get install -y qemu-user-static binfmt-support

      - run: docker buildx create --use

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Icinga Web 2
        run: git clone https://github.com/Icinga/icingaweb2.git

      - name: Build and Push
        run: ./build.bash ./icingaweb2 release push ghcr.io/hbro/icingaweb2
